language: java
services:
  - docker
sudo: required
jdk:
 - openjdk11
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean test
  - mvn clean package -Pnative -Dnative-image.container-runtime=docker