language: java
services:
  - docker
sudo: required
jdk:
 - openjdk11
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean test -B
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pnative -Dnative-image.container-runtime=docker