language: java
install: "mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pnative -Dnative-image.container-runtime=docker"
script:
  - mvn clean test -B
services:
  - docker
sudo: required
jdk:
 - openjdk11
cache:
  directories:
  - $HOME/.m2

