version: "3.7"


services:
  psql:
    container_name: "postgresql-container"
    image: "postgres:11.3"
    ports:
      - "5432:5432"
    volumes:
      - "psql-data:/var/lib/postgresql/data"
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB  

  pdf-analyzer:
    container_name: "invoice-pdf-analyzer-container"
    build:
      context: .
      dockerfile: Dockerfile.pdfanalyzer
    image: cvt/invoice-pdf-analyzer:latest
    ports:
      - "8080:8080"
    depends_on:
      - psql      
    environment:
      - WAIT_HOSTS=psql:5432
      - WAIT_HOSTS_TIMEOUT=8
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://psql:5432/${POSTGRES_DB}
      - QUARKUS_DATASOURCE_USERNAME=${POSTGRES_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
# it's not possible to specify bellow property env due to missing quarkus support for it
# https://github.com/quarkusio/quarkus/issues/2933     
#      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=none

volumes:
  psql-data:

networks:
  default:
    external:
      name: cvt-oss

